###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
  "idt": 1,
  "nombre": "Blusa Mujer Manga Corta Nudo",
  "precio": 50,
  "stock": 10,
  "codigo": "P001",
  "categoria": "mujer",
  "img": "/imagenes/mujer1.webp"
},
{
  "idt": 2,
  "nombre": "Blusa Mujer Sin Manga Patty",
  "precio": 55,
  "stock": 5,
  "codigo": "P002",
  "categoria": "mujer",
  "img": "/imagenes/mujer2.webp"
},
{
  "idt": 3,
  "nombre": "Vestido Mujer Lazo",
  "precio": 52,
  "stock": 8,
  "codigo": "P003",
  "categoria": "mujer",
  "img": "/imagenes/mujer3.webp"
},
{
  "idt": 4,
  "nombre": "Enterizo Largo Sin Mangas",
  "precio": 52,
  "stock": 8,
  "codigo": "P004",
  "categoria": "mujer",
  "img": "/imagenes/mujer4.webp"
},
{
  "idt": 5,
  "nombre": "Enterizo Jumper Mujer",
  "precio": 52,
  "stock": 8,
  "codigo": "P005",
  "categoria": "mujer",
  "img": "/imagenes/mujer5.webp"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/6137e2bb2e329eb206b0073e HTTP/1.1

###
DELETE http://localhost:9000/api/users/6137e1725461c36eba8b2ce4 HTTP/1.1

###
PUT http://localhost:9000/api/users/6137e2412e329eb206b0073c HTTP/1.1
Content-Type: application/json

{
  "name": "John Conway",
  "age": 80,
  "email": "johnconway@email.com"
}